version: "3.7"
services:
  tboard:
    image: tensorflow/tensorflow:1.15.2-gpu-py3-jupyter
    container_name: tboard
    restart: "no"
    init: true
    ports: 
      - "8686:8686"
    volumes:
    - ./tfCheckpoints:/tfCheckpoints
    command: >
      bash -c "source /etc/bash.bashrc &&
               # Launch tensorboard
               tensorboard --logdir="/tfCheckpoints" --port 8686"

  tfjupyter:
    #image: tensorflow/tensorflow:1.15.2-gpu-py3-jupyter
    image: freezurbern/dh-pytfcuda
    container_name: tfjupyter
    # Don't silently restart - let us know by staying shut down
    restart: "no"
    init: true
    ports:
      - "8484:8484"
    volumes:
    # Input Data (Read Only)
    - ./inputData:/tf/inputData:ro
    # Notebooks for jupyter notebook (Read/Write)
    - ./pycode:/tf/pycode:rw
    # Deep learning checkpoint files (Read/Write)
    - ./tfCheckpoints:/tf/tfCheckpoints:rw
    # Configuration files for jupyter notebook (Read Only)
    - ./jn-config:/tf/jn-config:ro
